### ISSUE TITLE
Avoid almost full recompilation in VS

### ISSUE THREAD

**Issue by johnnyontheweb** [oofem/oofem#138]
Hello, 
I'm compiling oofem in visual studio, and as per the latest commits on git hash and compilation info, **a full rebuild is always required even if there's no changes in code**.
I'm guessing why and I found out that rhe directive `#include "oofemcfg.h"` is included also in engngm.c, so every time compilation starts, oofem_version.h is updates, hence oofemcfg, and then the build of engngm.c must be updated, causing almost a full recompilation.

Could this be avoided? I believe oofemcfg.h could be included only only in main.c.

**Comment by fponta** [comment]
Hi @bpatzak ,

I've noticed an attempt was made to address this issue, however the code isn't properly building the shared lib for Windows:

The problem lies with the fact that MSVC needs `__declspec(dllexport)`/`__declspec(dllimport)` to be used correctly, that is the DLL is built with `dllexport`, the executable with `dllimport`, because the executable needs the symbols in DLL and not the viceversa.

Currently `oofemcfg.C` is the file defining the macros and constants, **resides in the executable** and therefore the DLL can't see them.

I suggest:
- moving oofemcfg.C inside the `core` library, so the definitions are always being shipped with the shared library which sort of makes sense.
- add the OOFEM_EXPORT macros to oofemcfg.h declarations, while removing it from oofemcfg.C
- revert recent changes to the CMakeLists.txt file which added `${oofem_SOURCE_DIR}/src/oofemcfg.C` all around, as now all targets will have the definitions for free.

_**P.S.**_ Kinda unrelated to all of the above, `assemblercallback.h` should import `oofemcfg.h` instead of `oofem_export.h` otherwise it doesn't build with the SHARED_LIB option off (my bad).

**Comment by bpatzak** [comment]
HI,
partially done now in devel branch ( https://github.com/oofem/oofem/commit/dc810bedb08fd9d2513ea66c383f5b5455e2d21a). 
I still need to check why assemblercallback.h needs to include oofemcfg.h. Also OOFEM_EXPORT macros still in oofemcfg.C  (Any reason why to move them to *.h?)

**Comment by fponta** [comment]
I guess you're working on Linux which seems exempt from all this mess?🤔 

> why assemblercallback.h needs to include oofemcfg.h

Because of the combination  https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html

oofemcfg.h is generated using [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html)
When `USE_SHARED_LIB` option is turned on, in oofemcfg.h.in, the line `@OOFEM_EXPORT_HEADER@` is replaced with `#include "oofem_export.h"` inside which the complete definition of the `OOFEM_EXPORT` macro will reside (the reason for this is the other half of this comment).

If `USE_SHARED_LIB` is turned off, the same `@OOFEM_EXPORT_HEADER@` line is replaced with a hardcoded definition of `OOFEM_EXPORT` (and other macros) to empty one, which basically means "no dlls are involved in this". Take a look at what happens in the CMakeLists.txt file.

---

> Any reason why to move them to *.h?

On windows with the `USE_SHARED_LIB` option turned on, the same header file (oofem_cfg.h) is used to compile different targets each with different preprocessor directives:
- in the dll, `OOFEM_EXPORT` translates to `__declspec(dllexport)` signalling that symbol is to be made public.
- in the exe, `OOFEM_EXPORT` translates to `__declspec(dllimport)` signalling that symbol will be picked up by loading a dll.

The opposite doesn't happen, that's why the code doesn't build and that's why I suggested moving the file to the other project.

So using the macro in the oofemcfg.h with something like:

```c++
OOFEM_EXPORT extern const char *PRG_VERSION;
OOFEM_EXPORT extern const char *OOFEG_VERSION;
...
```

ensures this import/export duality between dll and exe.

https://learn.microsoft.com/en-us/cpp/build/importing-into-an-application-using-declspec-dllimport?view=msvc-170

By the way other .h files in the codebase use the `OOFEM_EXPORT` macro so that stuff defined in the dll can be loaded by the exe. See for example `OOFEMTXTDataReader` which is defined in the dll but needs to be used also by the main.C in the exe.

**Comment by mehrpay** [comment]
Thanks for bringing this issue up. I think the oofem should be compilable regardless of the OS (windows, mac and Linux).
I could compile the OOFEM in Windows by commenting out some problematic parts in my local clone, but I hope @fponta 's suggestion can resolve this issue permanently and in a more graceful way.

**Comment by bpatzak** [comment]
The combination of user-configuration and OS specific settings in oofemcfg.h is confusing.
I would then suggest cleaner approach: 
- separate info on user configuration of the solver to oofemcfg.h (already most of it)
- put OS and environment configuration to new oofemenv.h (that should replace what was in oofem_export.h and partially what was in oofemcfg.h (#define HAVE_CBRT 1 etc).

Regarding applying OOFEM_EXPORT in header file, this is ok.

**Comment by johnnyontheweb** [comment]
Hello,
are you planning to merge it in master? thanks

**Comment by johnnyontheweb** [comment]
Hi,
still not working in Windows, even using the cited commit.

```
Error C2065	'PRG_HEADER': identificatore non dichiarato	sm	.\oofem\src\sm\EngineeringModels\varlinearstability.C	154		
Error C2065	'PRG_HEADER': identificatore non dichiarato	sm	.\oofem\src\sm\EngineeringModels\responsespectrum.C	206		
Error C2065	'PRG_HEADER': identificatore non dichiarato	sm	.\oofem\src\sm\EngineeringModels\dummyenum.C	157		
Error LNK1120	5 esterni non risolti	liboofem	.\oofem\new64\Release\oofem.dll	1		
Error C1083	Non è possibile aprire il file inclusione: 'oofem_version.h': No such file or directory	oofem	.\oofem\src\oofemcfg.C	1		
Error LNK2019	riferimento al simbolo esterno "char const * const HOST_TYPE" (?HOST_TYPE@@3PEBDEB) non risolto nella funzione "public: virtual void __cdecl oofem::SolutionStatusExportModule::initialize(void)" (?initialize@SolutionStatusExportModule@oofem@@UEAAXXZ)	liboofem	.\oofem\new64\solutionstatusexportmodule.obj	1		
Error LNK2019	riferimento al simbolo esterno "char const * const MODULE_LIST" (?MODULE_LIST@@3PEBDEB) non risolto nella funzione "public: virtual void __cdecl oofem::SolutionStatusExportModule::initialize(void)" (?initialize@SolutionStatusExportModule@oofem@@UEAAXXZ)	liboofem	.\oofem\new64\solutionstatusexportmodule.obj	1		
Error LNK2019	riferimento al simbolo esterno "char const * const OOFEM_GIT_HASH" (?OOFEM_GIT_HASH@@3PEBDEB) non risolto nella funzione "public: virtual void __cdecl oofem::SolutionStatusExportModule::initialize(void)" (?initialize@SolutionStatusExportModule@oofem@@UEAAXXZ)	liboofem	.\oofem\new64\solutionstatusexportmodule.obj	1		
Error LNK2019	riferimento al simbolo esterno "char const * const PRG_VERSION" (?PRG_VERSION@@3PEBDEB) non risolto nella funzione "public: virtual void __cdecl oofem::SolutionStatusExportModule::initialize(void)" (?initialize@SolutionStatusExportModule@oofem@@UEAAXXZ)	liboofem	.\oofem\new64\solutionstatusexportmodule.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\dummyenum.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\linearstability.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\varlinearstability.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\incrementallinearstatic.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\responsespectrum.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\outputexportmodule.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\engngm.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\staggeredproblem.obj	1		
Error LNK2001	simbolo esterno "char const * const PRG_HEADER" (?PRG_HEADER@@3PEBDEB) non risolto	liboofem	.\oofem\new64\eigenvaluedynamic.obj	1	
```

**Comment by johnnyontheweb** [comment]
Thanks, seems to work now. It would be nice to have:
https://github.com/oofem/oofem/commit/05768027a1be414d150e3d6644d440eb4518c320
https://github.com/oofem/oofem/commit/dbcaee8a75b83e40b043ba537ced29a04f43aa2a
on master branch too.
