### ISSUE TITLE
Advice needed for export module for lattice models

### ISSUE THREAD

**Issue by githubgrasp** [oofem/oofem#70]
I am trying to incorporate the vtkxm export modules for lattice models into oofem.

The main different to exisitng vtkxml modules is that in addition to the  normal nodes, elements and data, it will need to plot also nodes of crossections (edges), cells (cross-section area in the form of a polygon) and data for the nodes.

These export modules will be very similar for sm and tm for lattice models. 

However, they are very different from the standard module. Therefore, I think it is worth to create a separate class for this, which inherits from the normal module. 
The question is where to place this class. If it is in oofemlib, then I have the problem that I don't know how to call the lattice specific functions for cross-section nodes, areas, etc as I have lattice elements in sm and tm but not in oofemlib. 

Would it make sense to create a latticeelement in oofemlib, which has some functionality common for sm and tm lattice elements, so that there is only one lattice exportmodule for both sm and tm?

**Comment by Micket** [comment]
I must admit I don't quite understand what the need, but, I'll just tackle the general question-

Based on my (very) limited understanding of the lattice problems, but as far as I understand;
1. Materials don't share anything with StructuralMaterial/TransportMaterials [**1**]
2. Elements don't share *much* with StructuralElement/TransportElement
While they do use the same engineering models, these are so generic that there isn't even much difference between StaticStructural or StationaryTransport. With some refactoring, we could reuse most code between them, and freely introduce another one, if needed.
Thus, my question is whether or not doing
```
lattice/core/
lattice/sm/
lattice/tm/
```
would be the most logical and clean approach? *I'm assuming that there won't be meshes with a mix of conventional elements and lattice elements. If there are.. then I have no suggestions.*

[**1**] Example; LatticeTransMat needs a "crackWidths" input, but since it was limited by the conventional conventional transport API, it insteads has to "go back" and fetch this input via `gp->giveElement()->giveCrackLengths`. See #27 
Had we designed an API that fits the needs of lattice TM materials, this need wouldn't be there, and the code would be much clearer, shorter.

I see all occurrences of `gp->giveElement()` and `#ifdef __SM__MODULE` or `#include "../sm/` as a clear sign that the design isn't right. 


In general, I think OOFEM suffers a bit from trying to merge different approaches in the same base class.

**Comment by githubgrasp** [comment]
One of the big problems in the past was to implement the interaction between sm and tm. You pointed out the example with the use of crack width in the transport material.
Even bigger problems we had with modelling the coupling in the other direction. We could use the same approach for taking into account fluid pressure on material response. 
However, considering additional boundary forces at nodes in sm due to fluid pressure in tm, was difficult for the lattice approach. We introduced special nodes for this (dirichlet and neumann coupling nodes). However, our approach that we used in old versions of oofem stopped working in the new version. One of the motivations on spending time to get it the lattice models working in current version is to get out sm/tm coupled models working again and extend it. So, if the approach that you suggest could improve this interaction, then this interaction would be more important than making the option of coupling of FE/Lattice easy. I am just now working on introducing the other tm lattice models and some post processing features so that we can use it for ongoing projects.
However, then I would like to work on extending the interaction between tm and sm models to be able to model more fluid induced fracture processes.


On Fri, 06 Dec 2019 23:11 +00:00, Mikael Öhman <notifications@github.com> wrote:
> I must admit I don't quite understand what the need, but, I'll just tackle the general question-

> Based on my (very) limited understanding of the lattice problems, but as far as I understand;

>  1. Materials don't share anything with StructuralMaterial/TransportMaterials [*1*]
>  2. Elements don't share *much* with StructuralElement/TransportElement
>  While they do use the same engineering models, these are so generic that there isn't even much difference between StaticStructural or StationaryTransport. With some refactoring, we could reuse most code between them, and freely introduce another one, if needed.
>  Thus, my question is whether or not doing
> `lattice/core/
lattice/sm/
lattice/tm/
`

**Comment by Micket** [comment]
Well, my only point is that is these lattice models/elements are completely incompatible with the "normal" SM and TM models anyway, there is not really any point in trying to force them into the same class hierarchy.

My concern is primary with the "health" of the code as a whole, as I think the maintainability, readability, suffers greatly if we try to put all types of special cases into base classes. Especially if there is no advantage to doing so.
For example, the material model code improved greatly as a result of moving the base class directly to Material, since it's inheritently different from .

Where the files are located is less of a concern, they are trivially moved if we decide on a better structure.

**Comment by githubgrasp** [comment]
OK, I understand now what you mean with this. I think that the structure that we have started (structural lattice elements in sm and transport lattice elements in tm) is fine. Based on my understanding of the structure of oofem, the sm lattice elements should have similar position as beam elements. We sometimes combine solid elements with beam elements. In the same way one could combine lattice elements in sm with solid elements. So, based on this there should not be a lattice element in oofemlib.  

I will close this issue now. My original question started because I tried wrote the vtkxmlexportmodule for the lattice models which have print the mid-crosssections. I have now done proposed something in the pull request that is open right now, which used the original structure with sm and tm.
